#!/bin/bash
# Pairs the journal app with the Health dashboard on this Mac: reads the dashboard's
# ingest token and writes it into Undercurrent/Generated/HealthDashboardPairing.swift,
# which is gitignored so the token never goes to GitHub. install-on-phone.sh runs this
# before every build; without it the app builds fine and simply doesn't sync.
set -uo pipefail
cd "$(dirname "$0")"

DASHBOARD_DIR="${DASHBOARD_DIR:-/Users/daviddesouza/Desktop/10 Projects/HealthDashboard}"
PORT="${DASHBOARD_PORT:-5181}"
OUT="Undercurrent/Generated/HealthDashboardPairing.swift"

if [ ! -d "$DASHBOARD_DIR" ] || ! command -v node >/dev/null 2>&1; then
  echo "Note: Health dashboard not found here; the app won't sync to it."
  exit 0
fi

TOKEN="$(cd "$DASHBOARD_DIR" && node --no-warnings -e "import('./server/db.js').then(m=>console.log(m.getSetting('ingestToken')))" 2>/dev/null | tail -n 1)"
if [[ -z "$TOKEN" || "$TOKEN" == "undefined" || "$TOKEN" == "null" || ! "$TOKEN" =~ ^[A-Za-z0-9._~+/=-]+$ ]]; then
  echo "Note: couldn't read the Health dashboard's token; the app won't sync to it."
  exit 0
fi

HOST="$(scutil --get LocalHostName 2>/dev/null || echo Davids-MacBook-Air)"
URL="http://$HOST.local:$PORT"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// Generated by pair-health-dashboard.sh — do not edit, do not commit (gitignored).
import Foundation

@objc(UndercurrentHealthDashboardPairing)
final class GeneratedHealthDashboardPairing: NSObject, HealthDashboardPairing {
    static var url: String { "$URL" }
    static var token: String { "$TOKEN" }
}
EOF
echo "→ Paired with the Health dashboard at $URL"
